// EXERCISE:
// You can write all the code natively (for cycles and such) or you can use some advanced functions which JS arrays provides in case you see them fit
// https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array
// There can be multiple solutions to each task, solve it as you see fit.
// You will work with array `numbers` which will be generated by code (code below) in every task.
// Write these functions:

// This block generates array with random length with values between 1-100
let numbers = []
const length = Math.ceil(Math.random() * 10) + 5
for (let i = 0; i < length; i = i + 1) {
  numbers.push(Math.ceil(Math.random() * 100))
}

// a) Function which will print to console a whole array
const printArray = (numbers) => {
  console.log(numbers)
}

console.log("Array: ")
printArray(numbers)

// b) Function which will print to console the length of array
const printLength = (numbers) => {
  console.log(numbers.length)
}

console.log("\nLength: ")
printLength(numbers)

// c) Function which will print to console the first element of array
const printFirstItem = (numbers) => {
  console.log(numbers[0])
}

console.log("\nFirst Item: ")
printFirstItem(numbers)

// d) Function which will print to console the last element
const printLastItem = (numbers) => {
  console.log(numbers[numbers.length - 1])
}

console.log("\nLast Item: ")
printLastItem(numbers)

// e) Function which will print to console the largest number (You can check Math functions)
const printLargestItem = (numbers) => {
  console.log(Math.max(...numbers))
}

console.log("\nLargest Item: ")
printLargestItem(numbers)

// f) Function which will print to console the smallest number (You can check Math functions)
const printSmallestItem = (numbers) => {
  console.log(Math.min(...numbers))
}

console.log("\nSmallest Item: ")
printSmallestItem(numbers)

// g) Function which will print to console the sum of all numbers in array (You can check reduce function)
const printSum = (numbers) => {
  const sum = numbers.reduce((accumulator, currentValue) => {
    return accumulator + currentValue
  }, 0)

  console.log(sum)
}

console.log("\nSum:")
printSum(numbers)

// h) Function which will print to console the difference between the largest and the smallest number (You can check Math functions)
const printSALDifference = (numbers) => {
  console.log(Math.max(...numbers) - Math.min(...numbers))
}

console.log("\nSALD Difference:")
printSALDifference(numbers)

const printAverage = (numbers) => {
  const sum = numbers.reduce((accumulator, currentValue) => {
    return accumulator + currentValue
  }, 0)

  console.log(sum / numbers.length)
}

console.log("\nAverage:")
printAverage(numbers)

// j) Function which will print to console the index of largest number (You can check Math functions)
const printLargestsIndex = (numbers) => {
  console.log(numbers.indexOf(Math.max(...numbers)))
}

console.log("\nLargest Index:")
printLargestsIndex(numbers)

// k) Function which will print to console the even numbers (not the array of even numbers),
// if array doesn't contain any even number, show text "Even number isn't in array"
const printEvenNums = (numbers) => {
  const evens = numbers.filter((num) => num % 2 === 0)

  console.log(evens)
}

console.log("\nEven Numbers:")
printEvenNums(numbers)

// l) Function which will multiple by 2 every number in array and print the array to console
// Example: printNumsMultipliedBy2([1,2,3]) -> [2,4,6]
const printNumsMultipliedBy2 = (numbers) => {
  const multiplied = numbers.map((num) => num * 2)
  console.log(multiplied)
}

console.log("\nMultiplied by 2:")
printNumsMultipliedBy2(numbers)
